name: Generate WSL NixOS Image Launcher

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Pull latest install.tar.gz
      run: |
        mkdir ./x64
        curl https://github.com/Elyhaka/NixOS-WSL/releases/download/0.0.2/install.tar.gz --output ./x64/install.tar.gz

    - name: Build latest version of launcher
      run: ./build.bat
